apiVersion: v1
kind: Pod
metadata:
  namespace: default
  labels:
    app: python-app
spec:
  containers:
  - name: python-container
    image: "" #enter your application dockerhub image here
  - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: python-appsvc
  namespace: default
spec:
  type: NodePort
  selector:
    app: python-app
  ports:
  - port: 8000
    targetPort: 8000
    
